# Generated by Django 3.2.5 on 2021-10-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210720_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
